### ISSUE TITLE
OTA Check failing on Xperia SP

### ISSUE THREAD

**Issue by smclt30p** [ResurrectionRemix/packages_apps_ResurrectionOTA#14]
The OTA Check is broken on the Xperia SP. logcat says that the server returns 200 but the check fails.

> 05-28 15:18:40.826  2778  8118 I SlimOTA : deviceName: huashan
> 05-28 15:18:40.894  2778  8118 I SlimOTA : downloadStatus: 200
> 05-28 15:18:40.976   649  1272 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@6b875a6 attribute=null, token = android.os.BinderProxy@4e2b6ec
> 05-28 15:18:44.619   649  1210 D WifiStateMachine: starting scan for "Atheros"-WPA_PSK with 2457
> 05-28 15:18:50.273   649  1219 D AudioService: Stream muted, skip playback
> 05-28 15:18:50.364  2778  4842 I SlimOTA : deviceName: huashan
> 05-28 15:18:50.430  2778  4842 I SlimOTA : downloadStatus: 200
> 05-28 15:18:50.519   649  1870 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@3fd2bfb attribute=null, token = android.os.BinderProxy@4e2b6ec
> 05-28 15:18:55.373   649  1219 D AudioService: Stream muted, skip playback
> 05-28 15:18:55.450  2778  4861 I SlimOTA : deviceName: huashan
> 05-28 15:18:55.510  2778  4861 I SlimOTA : downloadStatus: 200
> 05-28 15:18:55.600   649   675 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@b6a493a attribute=null, token = android.os.BinderProxy@4e2b6ec

![screenshot_11](https://cloud.githubusercontent.com/assets/13964795/15627556/24f0f4d8-24e8-11e6-88c0-eed3fddcd065.png)
![screenshot_20160528-151823](https://cloud.githubusercontent.com/assets/13964795/15627571/57a3cbd0-24e8-11e6-858b-9c795d92d34f.png)

**Comment by akhilnarang** [comment]
@smclt30p that's cause its the first build =)
When I release a new build, that's when I will add the new stuff, and you'll get notifications and links here too =)

**Comment by smclt30p** [comment]
I'm sorry, but I don't think this is the first build. There is a build, version v5.6.5 on 20160329.

https://s.basketbuild.com/filedl/devs?dev=resurrectionremix&dl=resurrectionremix/huashan/ResurrectionRemix-M-v5.6.5-20160329-huashan.zip

**Comment by akhilnarang** [comment]
that was by old maintainer @furrydaus he's busy now so I took over
OK, i'll add OTA Stuff now since you seem to want it so badly :3

**Comment by smclt30p** [comment]
I don't want it badly. I want that it works. You should also update yourself in Settings > About > About Resurrection > Devices and Maintainers, @furrydaus is still there.

**Comment by akhilnarang** [comment]
Yep, I will 
It'll work when it has to work, i.e. it'll start working once a new build is released

**Comment by smclt30p** [comment]
Hold on, so when there is no new build the check fails with a message "Can't check update." ?

If that is the case, there is something wrong here. The "Can't check update" dialog is shown if the OTADevice is null when passed. 

```
 @Override
    protected void onPostExecute(OTADevice device) {
        super.onPostExecute(device);

        if (device == null) {
            showToast(R.string.check_update_failed);
        } else {
            String latestVersion = device.getLatestVersion();
            boolean updateAvailable = OTAVersion.checkServerVersion(latestVersion, mContext);
            if (updateAvailable) {
                showNotification(mContext);
            } else {
                showToast(R.string.no_update_available);
            }
            AppConfig.persistLatestVersion(latestVersion, mContext);
            LinkConfig.persistLinks(device.getLinks(), mContext);
        }

        AppConfig.persistLastCheck(mContext);

        hideWaitDialog();

        mInstance = null;
    }
```

`device` is null, it shows a toast with the `check_update_failed` defined string. If there is no build, shouldn't a `showToast(R.string.no_update_available);` occur?

**Comment by akhilnarang** [comment]
Nope
The point is I haven't put huashan info into the xml file yet
I would've done so when I was gonna release the 2nd build
And then all builds would show it
Doing it now since you seem to not like it missing :3

**Comment by akhilnarang** [comment]
@smclt30p https://github.com/ResurrectionRemix/OTA/commit/ffa39dba4c2d036bbab30c5322b0c781b3a52892 should fix it :3

**Comment by smclt30p** [comment]
That wasn't hard, was it?

![screenshot_20160528-183540](https://cloud.githubusercontent.com/assets/13964795/15628509/190e0258-2503-11e6-9435-78fa209c2e7f.png)

Please, in the future, don't explain why something is broken and close the issue, but try to fix it.

**Comment by akhilnarang** [comment]
Wasn't hard at all, I just never felt it necessary at the current time :3

**Comment by Furrydaus** [comment]
Please refrain from being sassy to my fellow devs. Let them take their time to do what they do best. I've got a life to handle and akhil has lots of things to maintain. Keep that in mind next time before you go around asking people to do things asap. You don't pay them a single cent

**Comment by smclt30p** [comment]
I did not force nor hurry him to fix this issue. I just did not find it apropriate that he closed the issue almlost as soon as I posted it, along with an explanation why it is broken. He could of left the issue open, and fix it another day. 

Unprofessional.

**Comment by akhilnarang** [comment]
Because it wasn't really an issue
The app is meant to provide an over-the-air update, as the name suggests
And when there is such an update available, it will notify you

**Comment by omkxr** [comment]
lmao

**Comment by koradiavatsal** [comment]
I prefer hangouts or telegram for chatting :v:
