### ISSUE TITLE
OTA Does not follow dark/light theming on 6.0 Lollipop

### ISSUE THREAD

**Issue by smclt30p** [ResurrectionRemix/packages_apps_ResurrectionOTA#15]
When "Automatic" or "Dark" is chosen in "Display and Lights", the OTA Activity is still white.

**Comment by akhilnarang** [comment]
Yep, OTA is a separate app as you can see this repo is different
The dark theme only affects the system apps where we added back what google removed
Gonna remove that option anyway.
