### ISSUE TITLE
usb tethering doesn't work

### ISSUE THREAD

**Issue by kaktus40** [ResurrectionRemix/packages_apps_ResurrectionOTA#16]
Hello,
I'm on oneplus two and I update my rom with ResurrectionRemix-M-v5.6.9-20160603-oneplus2.zip.
Since this update, I can't use use tethering (my linux mint doesn't connect to my phone when I choose usb sharing connexion). With other phone and with same PC, I can use this ability.

**Comment by akhilnarang** [comment]
Please post this issue on XDA thread so maintainer (@Bun-Bun69) can look into it
