### ISSUE TITLE
Can't Check Update

### ISSUE THREAD

**Issue by HostZero** [ResurrectionRemix/packages_apps_ResurrectionOTA#17]
I am on RR 5.7.1 Previous Build where as I am checking for 20160727 build it just replys can't check update.
![img-20160729-wa0001](https://cloud.githubusercontent.com/assets/17039813/17235936/a76f3aaa-5562-11e6-80ff-d5c402e0ca3a.jpg)

**Comment by akhilnarang** [comment]
Don't report here, report it to your device maintainer
