### ISSUE TITLE
Problem with ota

### ISSUE THREAD

**Issue by micky387** [ResurrectionRemix/packages_apps_ResurrectionOTA#7]
Hi.
I have a problem with ResurrectionOTA
I have added ota.xml and ota_conf but this apk cant check update...
Do you have any idea ??
here,my config https://github.com/micky387/OTA/tree/master
best reagrds

**Comment by akhilnarang** [comment]
In GApps URL make & to &amp; like it is in ROM URL

Also verify XML with online XML validator

**Comment by micky387** [comment]
ok,thanks.
I dont know why copy/past was failed the first time..
Sorry for this.
regards.
Closing issue
