### ISSUE TITLE
Use OpenDelta

### ISSUE THREAD

**Issue by regalstreak** [ResurrectionRemix/packages_apps_ResurrectionOTA#9]
Use opendelta for delta updates _(If you are interested)_
Changed the package names and stuff to rr ota's so that it shows in configurations/updates

https://github.com/regalstreak/packages_apps_OpenDelta

@akhilnarang @westcripp @varund7726

**Comment by varund7726** [comment]
We are too busy fixing lag
Cant Work on anything new till this is fixed

**Comment by akhilnarang** [comment]
we don't have server to use it

**Comment by regalstreak** [comment]
i know. I was just letting you all know that this can be implemented too :p 
FTP servers are cheap? serverhub.com is a good suggestion
I could provide you all a gerrit, but bandwidth would be a problem :/
Tip: Use github student credit :p
